# Auto-label PRs based on changed files

documentation:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'
    - '**/LICENSE'

core:
- changed-files:
  - any-glob-to-any-file:
    - 'src/**/*.ts'

workflow:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - '.github/workflows/*'

dependencies:
- changed-files:
  - any-glob-to-any-file:
    - 'package.json'
    - 'package-lock.json'

types:
- changed-files:
  - any-glob-to-any-file:
    - 'src/types.ts'
